# Generated by Django 2.0.13 on 2019-06-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemNum', models.IntegerField()),
                ('problemName', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('answerRate', models.FloatField()),
            ],
        ),
    ]
